# Generated by Django 4.0 on 2022-02-07 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Krankenhaus',
                'verbose_name_plural': 'Krankenhäuser',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50, verbose_name='Hersteller')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titel')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('is_instructor', models.BooleanField(default=False, verbose_name='MPG-Beauftragter')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='geraete.company', verbose_name='Krankenhaus')),
                ('instructor_for', models.ManyToManyField(related_name='instructors', to='geraete.Device', verbose_name='Einweiser für')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_users', to='geraete.company', verbose_name='Krankenhaus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_groups', to='geraete.company', verbose_name='Krankenhaus')),
                ('devices', models.ManyToManyField(to='geraete.Device', verbose_name='Einzuweisende Geräte')),
            ],
            options={
                'verbose_name': 'Berufsgruppe',
                'verbose_name_plural': 'Berufsgruppen',
            },
        ),
        migrations.CreateModel(
            name='PrimaryInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('instructor', models.CharField(max_length=50, verbose_name='Einweiser')),
                ('device_company', models.CharField(max_length=50, verbose_name='Firma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_instructions', to='geraete.company', verbose_name='Krankenhaus')),
                ('devices', models.ManyToManyField(related_name='primaryinstructions', to='geraete.Device', verbose_name='Geräte')),
                ('instructed', models.ManyToManyField(related_name='primaryinstructions', to='geraete.Employee', verbose_name='Eingewiesene')),
            ],
            options={
                'verbose_name': 'Ersteinweisung',
                'verbose_name_plural': 'Ersteinweisungen',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='geraete.company', verbose_name='Krankenhaus')),
                ('devices', models.ManyToManyField(related_name='instructions', to='geraete.Device', verbose_name='Geräte')),
                ('instructed', models.ManyToManyField(related_name='instructions', to='geraete.Employee', verbose_name='Eingewiesene')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='held_instructions', to='geraete.employee', verbose_name='Einweiser')),
            ],
            options={
                'verbose_name': 'Einweisung',
                'verbose_name_plural': 'Einweisungen',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='prof_group',
            field=models.ManyToManyField(blank=True, to='geraete.ProfessionalGroup', verbose_name='Berufsgruppe'),
        ),
        migrations.CreateModel(
            name='DeviceCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_cats', to='geraete.company', verbose_name='Krankenhaus')),
            ],
            options={
                'verbose_name': 'Gerätekategorie',
                'verbose_name_plural': 'Gerätekategorien',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.devicecat', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='geraete.company', verbose_name='Krankenhaus'),
        ),
    ]
