# Generated by Django 4.0 on 2021-12-11 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(max_length=50, verbose_name="Hersteller"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Gerät",
                "verbose_name_plural": "Geräte",
            },
        ),
        migrations.CreateModel(
            name="DeviceCat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=50, verbose_name="Kategorie"),
                ),
            ],
            options={
                "verbose_name": "Gerätekategorie",
                "verbose_name_plural": "Gerätekategorien",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Nachname"),
                ),
                (
                    "company",
                    models.CharField(
                        default="KHMUE", max_length=50, verbose_name="Firma"
                    ),
                ),
                ("is_instructor", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geraete.device",
                    ),
                ),
                (
                    "instructed",
                    models.ManyToManyField(
                        related_name="instructions", to="geraete.Employee"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"is_instructor": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_instructions",
                        to="geraete.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einweisung",
                "verbose_name_plural": "Einweisungen",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geraete.devicecat",
            ),
        ),
    ]
