# Generated by Django 4.0 on 2021-12-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geraete", "0002_professionalgroup_employee_prof_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="is_primary",
            field=models.BooleanField(
                default=False, verbose_name="Ersteinweisung"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_instructor",
            field=models.BooleanField(default=False, verbose_name="Einweiser"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="prof_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geraete.professionalgroup",
                verbose_name="Berufsgruppe",
            ),
        ),
    ]
