# Generated by Django 4.0 on 2021-12-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "geraete",
            "0003_instruction_is_primary_alter_employee_is_instructor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="instructor_for",
            field=models.ManyToManyField(
                related_name="instructors",
                to="geraete.Device",
                verbose_name="Einweiser für",
            ),
        ),
        migrations.AddField(
            model_name="professionalgroup",
            name="devices",
            field=models.ManyToManyField(
                to="geraete.Device", verbose_name="Einzuweisende Geräte"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geraete.devicecat",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_instructor",
            field=models.BooleanField(
                default=False, verbose_name="MPG-Beauftragter"
            ),
        ),
    ]
