# Generated by Django 4.0 on 2021-12-30 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geraete", "0005_remove_instruction_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="devices",
            field=models.ManyToManyField(
                related_name="instructions",
                to="geraete.Device",
                verbose_name="Geräte",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="instructed",
            field=models.ManyToManyField(
                related_name="instructions",
                to="geraete.Employee",
                verbose_name="Eingewiesene",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"is_instructor": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="held_instructions",
                to="geraete.employee",
                verbose_name="Einweiser",
            ),
        ),
        migrations.CreateModel(
            name="PrimaryInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Datum"
                    ),
                ),
                (
                    "instructor",
                    models.CharField(max_length=50, verbose_name="Einweiser"),
                ),
                (
                    "device_company",
                    models.CharField(max_length=50, verbose_name="Firma"),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="primaryinstructions",
                        to="geraete.Device",
                        verbose_name="Geräte",
                    ),
                ),
                (
                    "instructed",
                    models.ManyToManyField(
                        related_name="primaryinstructions",
                        to="geraete.Employee",
                        verbose_name="Eingewiesene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ersteinweisung",
                "verbose_name_plural": "Ersteinweisungen",
            },
        ),
    ]
